services:
  redis:
    image: redis:8.0
    command: ['redis-server']
    ports:
      - 6379:6379

  app:
    image: valepaska-app
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: valepaska-app
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
     - 8080:3000
    depends_on:
      - redis