services:
  backend:
    image: valepaska-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    container_name: valepaska-backend-dev
    ports:
      - 3000:3000
  redis:
    image: redis:8.0
    command: ['redis-server']
    ports:
      - 6379:6379

  app:
    image: valepaska-front-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - VITE_NODE_ENV=development
      - VITE_BACKEND_URL=http://localhost:5173
    container_name: valepaska-front-dev
    ports:
      - 5173:5173