import type { Card } from '../types/Card';

const deck: Card[] = [
  { name: 'C2', value: 2 },
  { name: 'D2', value: 2 },
  { name: 'H2', value: 2 },
  { name: 'S2', value: 2 },
  { name: 'C3', value: 3 },
  { name: 'D3', value: 3 },
  { name: 'H3', value: 3 },
  { name: 'S3', value: 3 },
  { name: 'C4', value: 4 },
  { name: 'D4', value: 4 },
  { name: 'H4', value: 4 },
  { name: 'S4', value: 4 },
  { name: 'C5', value: 5 },
  { name: 'D5', value: 5 },
  { name: 'H5', value: 5 },
  { name: 'S5', value: 5 },
  { name: 'C6', value: 6 },
  { name: 'D6', value: 6 },
  { name: 'H6', value: 6 },
  { name: 'S6', value: 6 },
  { name: 'C7', value: 7 },
  { name: 'D7', value: 7 },
  { name: 'H7', value: 7 },
  { name: 'S7', value: 7 },
  { name: 'C8', value: 8 },
  { name: 'D8', value: 8 },
  { name: 'H8', value: 8 },
  { name: 'S8', value: 8 },
  { name: 'C9', value: 9 },
  { name: 'D9', value: 9 },
  { name: 'H9', value: 9 },
  { name: 'S9', value: 9 },
  { name: 'C10', value: 10 },
  { name: 'D10', value: 10 },
  { name: 'H10', value: 10 },
  { name: 'S10', value: 10 },
  { name: 'CJ', value: 11 },
  { name: 'DJ', value: 11 },
  { name: 'HJ', value: 11 },
  { name: 'SJ', value: 11 },
  { name: 'CQ', value: 12 },
  { name: 'DQ', value: 12 },
  { name: 'HQ', value: 12 },
  { name: 'SQ', value: 12 },
  { name: 'CK', value: 13 },
  { name: 'DK', value: 13 },
  { name: 'HK', value: 13 },
  { name: 'SK', value: 13 },
  { name: 'CA', value: 14 },
  { name: 'DA', value: 14 },
  { name: 'HA', value: 14 },
  { name: 'SA', value: 14 },
];

export default deck;
