name: Testing And Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]    
    types: [opened, synchronize]

jobs:
  Run_Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: setup Node.js   
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: lint frontend
        working-directory: ./frontend
        run: npm run lint

      